### PR TITLE
Adjust VersionString parsing and add regression test

### PR DESCRIPTION
**Pull request by Ruteri**
## 📝 Summary

Adds a failing test case for parsing version string.
I believe the reason for this was this change https://github.com/flashbots/go-boost-utils/pull/27/files#diff-fe73f46e4cff48b9331df45e0200f2114ba1613b186bb511ef35e01bfbf22a73
I'm not sure if I should just revert to using string for the version field, or there's some additional requirements for the type and I should adjust the parsing of the VersionString.

## ⛱ Motivation and Context

After upgrading to newest version of the library, mev-boost's tests fail due to incorrect parsing of VersionString

## 📚 References

https://ethereum.github.io/builder-specs/#/Builder/getHeader

---

## ✅ I have run these commands

* [ ] `make lint`
* [ ] `make test`
* [ ] `go mod tidy`

### CODE REVIEW

**Comment by Ruteri** [comment]
Cc @jtraglia @metachris

**Comment by jtraglia** [comment]
Hey there @Ruteri. Yes, I made that change because the `FuzzRoundTripGetHeaderResponse` and `FuzzRoundTripGetPayloadResponse` tests were failing: https://github.com/flashbots/go-boost-utils/pull/27#issuecomment-1187459372. Sorry, I was unaware of the integration issue.

If you want a quick fix, you can revert those version fields to `string` and remove these two tests:

https://github.com/flashbots/go-boost-utils/blob/16711e59c92140ce405a8d8e26a8c787caec3289/types/builder_fuzz_test.go#L304-L308

https://github.com/flashbots/go-boost-utils/blob/16711e59c92140ce405a8d8e26a8c787caec3289/types/builder_fuzz_test.go#L330-L334

Personally, I would like to see those two fuzzing tests added back later.

**Comment by jtraglia** [comment]
Ah sorry. This is my fault. The length check is incorrect here (below). It should be `if len(b) < 2`.

https://github.com/flashbots/go-boost-utils/blob/16711e59c92140ce405a8d8e26a8c787caec3289/types/common.go#L377-L383

**Comment by jtraglia** [comment]
But with that change, it still fails the fuzzing tests. So yeah, just revert those version fields back to strings if you want. You'll also want to review the two tests: `FuzzRoundTripGetHeaderResponse` and `FuzzRoundTripGetPayloadResponse`.

```diff
Diff:
--- Expected
+++ Actual
@@ -1,3 +1,3 @@
 (*types.GetHeaderResponse)({
- Version: (types.VersionString) (len=374) "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"",
+ Version: (types.VersionString) (len=375) "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\\"",
  Data: (*types.SignedBuilderBid)({
```

**Review by metachris — APPROVED** [review]

**Review by jtraglia — APPROVED** [review]
The fuzzing tests will fail if run long enough, but at least this works. We can fix it later.

**Pull request merged**
